name: Build Ios Test

# 모든 브랜치에 push되었을때 실행
on: push

# on:
#   push:
# - 'frontend/**' -> frontend/**' 패턴에 매칭되는 모든 파일이 변경되었을때 실행
# branches: [test/CICD-hojung] -> 특정 브랜치에 push될 때만 실행

jobs:
  build:
    name:
      ios CD Test
      # job이 실행될 환경 - 최신 mac os
    runs-on: macos-latest

    # runs-on: macos-14 # 실행환경 설정

    steps:
      - name: Show self-hosted machine infomation
        run: uname -a

      - name: 체크아웃 # CI서버로 파일 복제
        uses: actions/checkout@v4
        # 특정 브랜치 복사할 때
        # with:
        #   ref: main

      - name: npm 설치
        run: npm install

      - name: Install pod dependency
        run: |
          cd ios && pod install --repo-update --clean-install
        # pod repo update, 캐쉬 지우기

      # xcode 15.3 버전으로 설정
      - name: Select Xcode 15.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: build check
        run: npm run ios
        # user:

      # - name: Build iOS (Release)
      #   uses: hojkim77/ios-build-action-KHJ@master
      #   with:
      #     project-path: ios/CareGiver.xcodeproj
      #     p12-base64: ${{ secrets.IOS_P12_BASE64 }}
      #     mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
      #     code-signing-identity: 'Apple Distribution'
      #     certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      #     team-id: ${{ secrets.IOS_TEAM_ID }}
      #     workspace-path: ios/CareGiver.xcworkspace
      #     output-path: 'CareGiver.ipa'
